bitcamp/bitcamp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('user.urls')),
] 


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
                   static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bitcamp/blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'
urlpatterns = [
    path('', home, name='home'),
    # path('posts/', posts, name="posts"),
    path('posts/', PostListView.as_view(), name='posts'),
    path('post/<int:pk>', post, name='post'),

    path('post_add/', post_add, name='post_add'),
    path('post/new/', PostCreateView.as_view(), name='create_post'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),

    path('categories/', CategoryListView.as_view(), name='categories'),
    path('category/<int:pk>', CategoryDetailView.as_view(), name='category'),

    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
]

bitcamp/user/urls.py
from django.urls import path
from .views import *


app_name='user'
urlpatterns = [
    path('', AutorListView.as_view(), name='authors'),
    path('<int:pk>/mentor/', MentorPostsView.as_view(), name='profile'),
    path('<int:pk>/', AuthorDetailView.as_view(), name='author'),
    path('<int:pk>/update/', UpdateAuthorView.as_view(), name='author_update'),
    path('<int:pk>/delete/', AuthorDeleteView.as_view(), name='author_delete'),

    path('login/', my_login, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register, name='register'),

]

bitcamp/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse, reverse_lazy
from sqlalchemy import null
from user.models import Author
from django.contrib.auth.models import User
from datetime import datetime, date
from ckeditor.fields import RichTextField


class Category(models.Model):
    category_name = models.CharField(max_length=124, unique=True)
    slug = models.SlugField(max_length=50, unique=True)
    describtion = models.TextField(blank=True)
    cat_image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self) -> str:
        return self.category_name

    def get_absolute_url(self):
        return reverse('home')


class Post(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    text = RichTextField(blank=True, null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category)
    image = models.ImageField(upload_to='post')

    def get_absolute_url(self):
        return reverse("blog:post", kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-create_date']


class Comment(models.Model):
    post = models.ForeignKey(
        Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, blank=True, null=True, default="anonymous")
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("blog:post", pk=self.post.pk)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-created_date']

bitcamp/blog/forms.py
from cProfile import label
from dataclasses import field
from pyexpat import model
from statistics import mode
from django import forms
from user.models import Author
from .models import Comment, Post


class CommentForm(forms.Form):
    text = forms.CharField(max_length=255, label='Comment Name No')
    author = forms.CharField(max_length=155)


class CommetModelForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 4, 'class': 'form-control', 'placeholder': 'Comments here ...',
        'label': 'Cooments',
    }))

    class Meta:
        model = Comment
        fields = ('text',)


class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ['author']

bitcamp/blog/views.py
from dataclasses import field
from distutils.util import execute
from http.server import executable
from django import forms
from django.shortcuts import redirect, render
from django.views.generic import ListView
from django.shortcuts import get_object_or_404, get_list_or_404
from . models import *
from django.db import models
from django.views.generic import (
    CreateView, UpdateView, DeleteView, DetailView, ListView)
from django.urls import reverse_lazy, reverse
from .models import Post
from .forms import CommetModelForm, PostModelForm
from django.contrib.auth import (authenticate, login, logout)
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.core.paginator import Paginator
from django.db.models import Q


class PostListView(ListView):
    model = Post
    paginate_by = 3

    def get_queryset(self):
        phrase_q = Q()
        q = self.request.GET.get('phrase')
        qa = self.request.GET.get('qa')
        if q:
            phrase_q &= (Q(text__icontains=q) | Q(description__icontains=q) | Q(title__icontains=q))
        if qa:
            phrase_q &= (Q(author__pk=qa))
        return Post.objects.filter(phrase_q).order_by('-pk')


def posts(request):
    phrase_q = Q()
    q = request.GET.get('phrase')
    if q:
        phrase_q &= (Q(text__icontains=q) | Q(description__icontains=q) | Q(title__icontains=q))
    post_list = Post.objects.filter(phrase_q).order_by('-pk')
    paginator = Paginator(post_list, 3)  # Show 3 posts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'blog/post_list.html', context)


# ავტომატურად უნდა იყოს ავტორიზებული უსერ პოსტის ავტორი
class PostCreateView(CreateView):
    fields = '__all__'
    model = Post

def post_add(request):
    form = PostModelForm()
    if request.method == 'POST':
        if request.user.is_staff:
            form = PostModelForm(request.POST, request.FILES)
            print(form)
            if form.is_valid():
                postm = form.save(commit=False)
                print(postm)
                # postm.author = request.user.id
                postm.author = Author.objects.get(pk=request.user.pk)
                postm.save()
                # კარგია თუ დამამახსოვრდება, სხვა დროსაც დამჭირდება
                form.save_m2m()
                return redirect(reverse("blog:posts"))
    return render(request, 'blog/post_form.html', {'form':form})


# აქ გვინდა რომ მხოლოდ პოსტის ავტორს შეეძლოს მოხვედრა
class PostUpdateView(UpdateView):
    fields = ('title', 'description', 'text', 'category', 'image')
    model = Post


# ეს არ შლის სურათს მედია ფაილიდან. გადასაწყვეტია ...
class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:posts')


class CommentDeleteView(DeleteView):
    model = Comment
    # აქ მირჩევნია იგივე გვერდზე დავრჩე
    success_url = reverse_lazy('blog:posts')
    

def home(request):
    posts = Post.objects.all()[0:10]
    return render(request, 'home.html', {'posts':posts})

def post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = CommetModelForm()

    if request.method == 'POST':
        form = CommetModelForm(request.POST)
        if form.is_valid():
            form.instance.post = post
            id = request.POST['id']
            form.instance.author = Author.objects.get(pk=id)
            form.save()
            return redirect(reverse("blog:posts"))
    return render(request, 'blog/post_detail.html', {'post': post, 'com_form':form})


# -----------------------------------------------
# აქედან იქნება Category

class CategoryListView(ListView):
    paginate_by = 3
    model = Category


class CategoryDetailView(DetailView):
    model = Category

bitcamp/blog/templates/blog/category_detail.html
{% extends 'base.html' %}
{% load static %}


{% block css_files %}
<link rel="stylesheet" href="{% static '/css/post_detail.css' %}">
{% endblock css_files %}

{% block content %}
<article class="single-post">
    <div class="single-post-header">
        <h1>{{ category.category_name | title }}</h1>
        <div class="author-div">
            <div class="author-img">
                <img src="{{ category.cat_image.url }}" style="height: 100%;" alt="პოსტის სურათი">
            </div>
            <p>{{ category.describtion | title }}</p>
        </div>
    </div>
</article>


<article class="single-post">
    <h3>
        Posts for this Category:
    </h3>

    <!-- <div class="categories"> -->

        <table class="table table-striped">
            <thead>
              <tr>
                <th>Category</th>
                <th>Title</th>
                <th>Author</th>
                <th>Image</th>
              </tr>
            </thead>
            {% for post in category.post_set.all %}
            <tbody>
              <tr>
                <td>{% for category in post.category.all  %}
                    <a href="{% url 'blog:category' category.pk %}" style="color: brown;">{{ category }}</a>
                    {% endfor %}</td>
                <td><a href="{% url 'blog:post' post.pk %}">{{ post.title | title }}</a></td>
                <td>{{ post.author | title }}</td>
                <td>
                    <img src="{{ post.image.url }}" style="width: 100px" alt="პოსტის სურათი">
                </td>
              </tr>

            </tbody>
            {% endfor %}
          </table>


    </div>

    <div class="single-post-body">
        <p>{{ post.text | safe }}</p>
    </div>
</article>

{% endblock %}

bitcamp/blog/templates/blog/category_list.html
{% extends 'base.html' %}
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'css/post_list.css' %}">
{% endblock %}

{% block js_files %}
<script src="{% static 'js/post_list.js' %} " defer></script>
{% endblock %}

{% block content %}


{% if category_list %}

<section class="posts-section container">
    <div class="post-list">
        {% for item in page_obj %}
        <article class="post">
            <div class="post-header">
                <h2><a href="{% url 'blog:category' item.pk %}">{{ item.category_name | title }} {{ item.pk }}</a></h2>
            </div>
            <div class="post-main-image-div">
                <a href="#">
                    <img src="{{ item.cat_image.url }}" alt="პოსტის სურათი">
                </a>
            </div>
            <div class="post-content">
                <p class="post-description">{{ item.describtion }}</p>
            </div>
    </article>
    {% endfor %}
    
    
    {% else %}
    <h3>   No List </h3>
    {% endif %}
</div>


<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; პირველი გვერდი</a>
        <a href="?page={{ page_obj.previous_page_number }}" class="page-number">{{ page_obj.previous_page_number }}</a>
        {% endif %}
        
        <span class="current">
                {{ page_obj.number }}
            </span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="page-number">{{ page_obj.next_page_number }}</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">ბოლო გვერდი &raquo;</a>
            {% endif %}
        </span>
    </div>
</section>



{% endblock %}

bitcamp/blog/templates/blog/comment_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>
    Delete Comment {{ comment }}?

</h1>
<form method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Delete">
    <a href="{% url 'user:profile' pk=user.pk %}">Cancel</a>

</form>
{% endblock %}

bitcamp/blog/templates/blog/mentor.html
{% extends 'base.html' %}
{% load static %}


{% block css_files %}
<link rel="stylesheet" href="{% static '/css/post_detail.css' %}">
{% endblock css_files %}

{% block content %}
<center>

    <h2>{{ user }}-ის ყველა პოსტი:</h2>
    <a href="{% url 'user:author_update' user.pk %}">პირადი მონაცემების განახლება</a>

    {% if post_list %}

    {% for post in post_list %}
    <article class="single-post">
        <div class="single-post-header">
            <h1>{{ post.title | title }}</h1>
            <div class="author-div">
                <i class="bi bi-person-circle"></i>
                <a href="{% url 'user:author' post.author.pk %}">
                    <p>{{ post.author | title }}</p>
                </a>
                <span>{{ post.create_date | date:"SHORT_DATE_FORMAT" }}</span>
            </div>
            <div class="categories">
                {% for category in post.category.all %}
                <a href="{% url 'blog:category' category.pk %}" class="single-category">
                    <p>{{ category }}</p>
                </a>
                {% endfor %}
                <a href="{% url 'blog:post_delete' post.pk %}" class="single-category text-danger">
                    <p>პოსტის წაშლა</p>
                </a>
            </div>
        </div>
        <div class="categories">
            {% for category in post.category.all %}
            <a href="{% url 'blog:category' category.pk %}" class="single-category">
                <p>{{ category }}</p>
            </a>
            {% endfor %}
            <a href="{% url 'blog:post_update' post.pk %}" class="single-category text-danger">
                <p>პოსტის განახლება</p>
            </a>
        </div>
        <div class="single-post-body">
            <p>{{ post.text | safe }}</p>
        </div>
    </article>
    <article class="single-post">
        <div class="single-post-header">
            <h4>
                კომენტარები:
            </h4>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">ავტორი</th>
                        <th scope="col">კომენტარი</th>
                        <th scope="col">თარიღი</th>
                        <th scope="col">წაშლა</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in post.comments.all %}
                    <tr>
                        <th scope="row">{{item.pk}}</th>
                        <td>{{item.author}}</td>
                        <td>{{item.text}}</td>
                        <td>{{item.created_date}}</td>
                        <td><a href="{% url 'blog:comment_delete' item.pk %}">კომენტარის წაშლა</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>

    </article>

    <br>
    {% endfor %}
    {% else %}
    <h3>
        {{user | title }} You Have not Posts Yet.
    </h3>
    {% endif %}

</center>

{% endblock %}

bitcamp/blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>
    Delete {{ post.title }}?

</h1>
<form method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Delete">
    <a href="{% url 'blog:post' pk=post.pk %}">Cancel</a>

</form>
{% endblock %}

bitcamp/blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}


{% block css_files %}
<link rel="stylesheet" href="{% static '/css/post_detail.css' %}">
{% endblock css_files %}

{% block js_files %}
<script src="{% static 'js/post_detail.js' %}" defer></script>
{% endblock js_files %}

{% block content %}

<article class="single-post">
    <div class="single-post-header">
        <h1>{{ post.title | title }}</h1>
        <div class="author-div">
            <i class="bi bi-person-circle"></i>
            <a href="{% url 'user:author' post.author.pk %}">
                <p>{{ post.author | title }}</p>
            </a>
            <span>{{ post.create_date | date:"SHORT_DATE_FORMAT" }}</span>
        </div>
        <div class="categories">
            {% for category in post.category.all %}
            <a href="{% url 'blog:category' category.pk %}" class="single-category">
                <p>{{ category }}</p>
            </a>
            {% endfor %}
        </div>
    </div>
    <div class="categories">
        {% for category in post.category.all %}
        <a href="{% url 'blog:category' category.pk %}" class="single-category">
            <p>{{ category }}</p>
        </a>
        {% endfor %}
    </div>
    <div class="single-post-body">
        <p>{{ post.text | safe }}</p>
    </div>
</article>
<article class="single-post">
    <div class="single-post-header">
        <h3>
            კომენტარები:
        </h3>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">ავტორი</th>
                    <th scope="col">კომენტარი</th>
                    <th scope="col">თარიღი</th>
                </tr>
            </thead>
            <tbody>
                {% for item in post.comments.all %}
                <tr>
                    <th scope="row">{{item.pk}}</th>
                    <td>{{item.author}}</td>
                    <td>{{item.text}}</td>
                    <td>{{item.created_date}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
    <br>
    <br>
    {% if user.is_authenticated %}
    <div style="width: 100%;">
        <form method="POST">
            {% csrf_token %}
            {{ com_form.as_p }}
            <input type="hidden" name="id" value="{{ user.pk }}">
            <input type="submit" value="კომენტარის დამატება">
        </form>
        {% endif %}
    </div>
</article>
<br>
<br>
<br>
<br>
<br>

{% endblock %}

bitcamp/blog/templates/blog/post_form.html
{% extends 'base.html' %}

{% block content %}
<center>

    {% if not form.instance.pk %}
    <h1>ახალი პოსტის დამატება!</h1>
    {% else %}
    <h1>პოსტის განახლება!</h1>
    {% endif %}
    
    <div class="jumbotron">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <input class="btn btn-warning" type="submit" value="Submit">
        </form>
    </div>
    
</center>
{% endblock %}

bitcamp/blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'css/post_list.css' %}">
{% endblock %}

{% block js_files %}
<script src="{% static 'js/post_list.js' %} " defer></script>
{% endblock %}

{% block content %}
<!-- აქ სიმბოლურად ვსვავ პოსტის დამატების ღილაკს, სადაც დაგჭირდება იქ გამოვიყენებთ.
    ეს ღილაკი გამოუჩნდებათ მარტო მენტორებს, ანუ ვინც იქნება is_staff სტატუსით -->
<center style="margin: auto;">
    {% if user.is_staff %}
    <br>
    <a class="create-button" href="{% url 'blog:post_add' %}">ახალი პოსტის შექმნა</a>
    <br>
    {% endif %}
    <br>

    <!--------------------------------------ძებნის ღილაკი, თუ გვჭირება, თუ არადა წავშალოთ------------------------------------------------------------>
    <div class="row">
        <form method="get" action="{% url 'blog:posts' %}">
            <input id="search_post" type="text" name="phrase" value="{{ request.GET.phrase }}">
            <label for="search_post"></label>
            <button class="create-button" type="submit" name="action">პოსტის ძებნა ფრაზით</button>
        </form>
    </div>
</center>

<!-- აქედან იწყება პოსტების გამოტანა იმდენის რამდენიც მითითებულია view-ში class PostListView(ListView):
paginate_by = 3 (რამდენი პოსტი გამოჩნდეს)    -->
{% if page_obj %}
<section class="posts-section container">
    <div class="post-list">

        {% for post in page_obj %}
        <article class="post">
            <div class="post-header">
                <h2><a href="{% url 'blog:post' post.pk %}">{{ post.title | title }}</a></h2>
                <div class="categories">

                    {% for category in post.category.all %}
                    <a href="{% url 'blog:category' category.pk %}">
                        <p class="category">{{ category }}</p>
                    </a>
                    {% endfor %}

                </div>
                <div class="post-author-div">
                    <i class="bi bi-person-circle"></i>
                    <form method="GET" action="{% url 'blog:posts' %}">
                        {% csrf_token %}
                        <button type="hidden" name="qa" value="{{ post.author.pk }}">
                            <p class="author-name">{{ post.author }}</p>
                        </button>
                        <!-- <input type="submit" value="{{ item }}-ს პოსტები"> -->
                    </form>
                </div>
            </div>
            <div class="post-main-image-div">
                <a href="{% url 'blog:post' post.pk %}">
                    <img src="{{ post.image.url }}" alt="პოსტის სურათი">
                </a>
            </div>
            <div class="post-content">
                <p class="post-description">{{ post.description }}</p>
            </div>
        </article>
        {% endfor %}

    </div>


    <div class="pagination">
        <span class="step-links">

            {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; პირველი გვერდი</a>
            <a href="?page={{ page_obj.previous_page_number }}" class="page-number">
                {{ page_obj.previous_page_number }}</a>
            {% endif %}

            <span class="current">
                {{ page_obj.number }}
            </span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="page-number">{{ page_obj.next_page_number }}</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">ბოლო გვერდი &raquo;</a>
            {% endif %}

        </span>
    </div>
</section>

{% else %}

No Post for this creteria!

{% endif %}

{% endblock %}