bitcamp/bitcamp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('user.urls')),
] 


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
                   static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bitcamp/blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'
urlpatterns = [
    path('', home, name='home'),
    # path('posts/', posts, name="posts"),
    path('posts/', PostListView.as_view(), name='posts'),
    path('post/<int:pk>', post, name='post'),

    path('post_add/', post_add, name='post_add'),
    path('post/new/', PostCreateView.as_view(), name='create_post'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),

    path('categories/', CategoryListView.as_view(), name='categories'),
    path('category/<int:pk>', CategoryDetailView.as_view(), name='category'),

    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
]

bitcamp/user/urls.py
from django.urls import path
from .views import *


app_name='user'
urlpatterns = [
    path('', AutorListView.as_view(), name='authors'),
    path('<int:pk>/mentor/', MentorPostsView.as_view(), name='profile'),
    path('<int:pk>/', AuthorDetailView.as_view(), name='author'),
    path('<int:pk>/update/', UpdateAuthorView.as_view(), name='author_update'),
    path('<int:pk>/delete/', AuthorDeleteView.as_view(), name='author_delete'),

    path('login/', my_login, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register, name='register'),

]

bitcamp/templates/includes/footer.html
<footer class="footer">
    <div class="footer-image-div">
        {% comment %} 
        აქ იქნება ბითქემფის ლოგო 
        <a href="{% url 'blog:home' %}">
            <img src="" alt="" class="bitcamp-logo">
        </a> 
        {% endcomment %}
        <h1>BitCamp logo</h1>
    </div>
    <nav class="footer-navigation">
        <a href="{% url 'blog:posts' %}" class="footer-nav-item">პოსტები</a> 
        <a href="#" class="footer-nav-item">კატეგორიები</a>

         {% if user.is_authenticated  %}
         <a href="#" class="footer-nav-item">პროფილი</a>
         <a href="#" class="footer-nav-item">ლოგაუთი</a>
         {% else %}
         <a href="#" class="footer-nav-item">ავტორიზაცია</a>
         <a href="#" class="footer-nav-item">რეგისტრაცია</a>
         {% endif %}
    </nav>
</footer>

bitcamp/templates/includes/navbar.html
<header class="header">
    <nav>
        <ul class="main-nav" 
            x-on:resize.window.debounce="isMobile = (window.innerWidth < 1000) ? true : false"
            x-data="{isMobile: (window.innerWidth < 1000) ? true : false}">
            <div class="first-nav-item" x-show="!isMobile" x-transition.duration.500ms>
                <a href="{% url 'blog:posts' %}"><li class="main-nav-item">პოსტები</li></a> 
                <a href="{% url 'blog:categories' %}"><li class="main-nav-item">კატეგორიები</li></a> 
                <!-- დროებით რომ იყოს ხელს თუ არ გიშლის, მარტივად რომ გადავიდე უსრებზე -->
                <a href="{% url 'user:authors' %}"><li class="main-nav-item">მენტორები</li></a> 
                
            </div>
            <div class="second-nav-item">
                <a href="{% url 'blog:home' %}"><li class="main-brand"> 🔥 BitCamp Blog</li></a>
                <i class="bi bi-list" @click="isMobile = !isMobile"></i>
            </div>
            <div class="third-nav-item"
                 x-show="!isMobile" x-transition.duration.500ms>

                 {% comment %} 
                აქ იქნება if check, თუ მომხმარებელი ავტორიზებულია მაშინ ეს
                {% endcomment %}

                {% if user.is_authenticated  %}
                <a href="{% url 'user:profile' user.pk %}"><li class="main-nav-item">სალამი {{user }}</li></a>
                <a href="{% url 'user:logout' %}"><li class="main-nav-item">ლოგაუთი</li></a>
                {% else %}
                <a href="{% url 'user:login' %}"><li class="main-nav-item">ავტორიზაცია</li></a>
                <a href="{% url 'user:register' %}"><li class="main-nav-item">რეგისტრაცია</li></a>
                {% endif %}
            </div>
        </ul>
    </nav>
</header>