bitcamp/bitcamp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('user.urls')),
] 


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
                   static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bitcamp/blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'
urlpatterns = [
    path('', home, name='home'),
    # path('posts/', posts, name="posts"),
    path('posts/', PostListView.as_view(), name='posts'),
    path('post/<int:pk>', post, name='post'),

    path('post_add/', post_add, name='post_add'),
    path('post/new/', PostCreateView.as_view(), name='create_post'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),

    path('categories/', CategoryListView.as_view(), name='categories'),
    path('category/<int:pk>', CategoryDetailView.as_view(), name='category'),

    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
]

bitcamp/user/urls.py
from django.urls import path
from .views import *


app_name='user'
urlpatterns = [
    path('', AutorListView.as_view(), name='authors'),
    path('<int:pk>/mentor/', MentorPostsView.as_view(), name='profile'),
    path('<int:pk>/', AuthorDetailView.as_view(), name='author'),
    path('<int:pk>/update/', UpdateAuthorView.as_view(), name='author_update'),
    path('<int:pk>/delete/', AuthorDeleteView.as_view(), name='author_delete'),

    path('login/', my_login, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register, name='register'),

]

bitcamp/user/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from sqlalchemy import null


class Author(User):
    image = models.ImageField(upload_to='profiles', blank=True, null=True)

    def __str__(self):
        return self.get_full_name()

    def get_absolute_url(self):
        return reverse('user:author', kwargs={'pk':self.pk})

    class Meta:
        verbose_name = _('Author')
        verbose_name_plural = _('Authors')

bitcamp/user/forms.py
from django import forms
from django.db.models.base import Model
from django.forms import fields
from django.forms.widgets import Input
from .models import Author
from django.forms import EmailField, CharField, IntegerField, DateInput, DateTimeInput
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError


class AuthorForm(forms.ModelForm):
    password1 = forms.CharField(
        label=_("პაროლი"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
            help_text=password_validation.password_validators_help_text_html(),
            )
    password2 = forms.CharField(
        label=_("დაადასტურე პაროლი"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
                help_text=_("Enter the same password as before, for verification."), 
        )
    username = forms.CharField(label=_("ნიკი"), strip=False)
    first_name = forms.CharField(label=_("სახელი"), strip=False)
    last_name = forms.CharField(label=_("გვარი"), strip=False)
    image = forms.CharField(label=_("სურათი"), strip=False)
    
    error_messages = {
        'password_mismatch': _('The two password fields don’t match.'),
        }

    class Meta:
        model = Author
        fields = ('username', 'first_name', 'last_name', 'image', 'password1', 'password2')
        widgets = {
            'first_name': Input(attrs={'placeholder': 'სახელი'}),
            'last_name': Input(attrs={'placeholder': 'გვარი', 'name':'სახელი'}),
            'password1': Input(attrs={'placeholder': 'სახელი'}),
            'password2': Input(attrs={'placeholder': 'სახელი'}),
        }


    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def _post_clean(self):
        super()._post_clean()
        # Validate the password after self.instance is updated with form data
        # by super().
        password = self.cleaned_data.get('password2')
        if password:
            try:
                password_validation.validate_password(password, self.instance)
            except ValidationError as error:
                self.add_error('password2', error)


    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

bitcamp/user/views.py
from re import template
from tkinter.ttk import Widget
from django.db import models
from django.shortcuts import get_object_or_404, render
from django.views.generic import (CreateView, UpdateView, DeleteView, DetailView, ListView)
from django.urls import reverse_lazy, reverse

from blog.models import Post
from .models import Author
from .forms import *
from django.contrib.auth import (authenticate, login, logout)
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic.detail import SingleObjectMixin
from django.views import View
from django.http import HttpResponseForbidden, HttpResponseRedirect


def home(request):
    return render(request, 'home.html')


class MentorPostsView(ListView):
    model = Author
    template_name = 'blog/mentor.html'

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user)


class AutorListView(ListView):
    queryset = Author.objects.filter(is_staff=True).order_by('?')
    model = Author


class AuthorDetailView(DetailView):
    model = Author


class CreateAuthorView(CreateView):
    fields = ('username', 'first_name', 'last_name', 'image', 'password')
    model = Author


class UpdateAuthorView(UpdateView):
    fields = ('username', 'first_name', 'last_name', 'image')
    model = Author


# ეს არ შლის სურათს მედია ფაილიდან. გადასაწყვეტია ...
class AuthorDeleteView(DeleteView):
    model = Author
    success_url = reverse_lazy('user:authors')


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = AuthorForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            # user.set_password(user.password1)
            user.save()
            if 'image' in request.FILES:
                user.image = request.FILES['image']
            user.save()
            # Registration Successful!
            registered = True
            return HttpResponseRedirect(reverse('user:login'))
        else:
            print(user_form.errors)
    else:
        user_form = AuthorForm()
    return render(request,'user/author_form.html',
                          {'form':user_form,
                           'registered':registered})


def my_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('blog:home'))
            else:
                # ალბათ ესეც გასასწორებელია.........................................
                return HttpResponse("Your account is not active.")
        else:
            # აქ გასასწორებელია. იგივე გვერდზე უნდა დარჩეს და მესიჯი გამოიტანოს............
            # return HttpResponseRedirect(reverse('blog:home'))
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'user/login.html', {})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('blog:home'))

bitcamp/user/templates/user/author_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>
    Delete {{ author.get_full_name }}?

</h1>
<form method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Delete">
    <a href="{% url 'user:author' pk=author.pk %}">Cancel</a>

</form>
{% endblock %}

bitcamp/user/templates/user/author_detail.html
{% extends 'base.html' %}

{% block content %}

<h2>
    Author detail Page!
</h2>
<div class="jumbotron">
    <h4 class="card-title">{{ author.get_full_name }}</h4>
        <div class="card" style="width:300px">
          <img class="card-img-top" src="{{ author.image.url }}" alt="Card image" style="width:100%">
          <div class="card-body">
            <p class="card-text">first_name: {{ author.first_name }}</p>
            <p class="card-text">last_name: {{ author.last_name }}</p>
            <p class="card-text">username: {{ author.username }}</p>
          </div>
        </div>
        <br>
        
        <div class="container">
            <p>
                <a class="btn btn-warning" href="{% url 'user:author_update' pk=author.pk %}">Update</a>
         
                <a class="btn btn-danger" href="{% url 'user:author_delete' pk=author.pk %}">Delete</a>
            </p>
        </div>
        
    </div>
{% endblock %}

bitcamp/user/templates/user/author_form.html
{% extends 'base.html' %}
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'css/author_form.css' %}"> 
{% endblock %}

{% block js_files %}
<script src="{% static 'js/author_form.js' %}" defer></script>

{% endblock js_files %}


{% block content %}






<section class="registration-section container card p-4 mt-4">
    {% if not form.instance.pk %}
    <h1>რეგისტრაცია</h1>
    {% else %}
    <h1>მონაცემების განახლება</h1>
    {% endif %}
    <form method="post" enctype="multipart/form-data" class="registration-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="submit-button">დარეგისტრირება</button>
    </form>
    <a href="{% url 'user:login' %}" class="authorisation-link">უკვე დარეგისტრირებული ხართ? გაიარეთ ავტორიზაცია</a> 
</section>


{% endblock %}

bitcamp/user/templates/user/author_list.html
{% extends 'base.html' %}

{% block content %}
<div class="bg-secondary text-red p-5 m-5">

    {% if author_list %}
    <h2>
        საიტის მენტორები:
    </h2>
    <br>
    <ol>
        {% for item in author_list %}
        <li>
            <ul>
                <li>
                    <form method="GET" action="{% url 'blog:posts' %}">
                        {% csrf_token %}
                        <input type="hidden" name="qa" value="{{ item.pk }}">
                        <input type="submit" value="{{ item }}-ს პოსტები">
                    </form>
                </li>
                <li>მეტსახელი: {{ item.username }}
                </li>
                <li>სახელი გვარი: {{ item.get_full_name }}</li>
            </ul>
        </li>
        <hr>
        {% endfor %}
    </ol>
    {% else %}
    <h3>
        No List
    </h3>
    {% endif %}

</div>
{% endblock %}

bitcamp/user/templates/user/login.html
{% extends 'base.html' %}
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock css_files %}

{% block content %}

<section class="d-flex flex-column justify-content-center align-items-center gap-4 container card p-4 mt-4">
  <h1>ავტორიზაცია</h1>
  <form method="post" action="{% url 'user:login' %}" class="login-form p-2">
    {% csrf_token %}
    <div class="d-flex justify-content-end align-items-center gap-2">
      <label for="username">ნიკი:</label>
      <input type="text" name="username" placeholder="Username">
    </div>
    <div class="d-flex justify-content-end align-items-center gap-2 w-100">
      <label for="password">პაროლი:</label>
      <input type="password" name="password">
    </div>
    <button class="submit-button" name="">ავტორიზაცია</button>

  </form>
  <a href="{% url 'user:register' %}" class="authorisation-link text-decoration-none">არ გაქვთ აქაუნთი?
    დარეგისტრირდით</a>
</section>

{% endblock %}